### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by jdkandersson** [canonical/is-charms-contributing-guide#11]
Type hints are helpful:

- When editing code as many code editors will use type hints for auto completion and indicating problems
- Make it easier to understand the code
- Can use `mypy` to statically check whether all types are correctly being used, e.g., for function parameters

There are a range of type hint levels we could adopt:

1. No type hints
2. Some type hints, e.g., for key functions and class/ instance variables
3. Use type hints extensively except where it is impractical to do so

To gain the maximum advantage of type hints and for code correctness to enhance stability of charms, I would recommend we go for (3).

**Comment by merkata** [comment]
> Type hints are helpful:
> 
> * When editing code as many code editors will use type hints for auto completion and indicating problems
> * Make it easier to understand the code
> * Can use `mypy` to statically check whether all types are correctly being used, e.g., for function parameters
> 
> There are a range of type hint levels we could adopt:
> 
> 1. No type hints
> 2. Some type hints, e.g., for key functions and class/ instance variables
> 3. Use type hints extensively except where it is impractical to do so
> 
> To gain the maximum advantage of type hints and for code correctness to enhance stability of charms, I would recommend we go for (3).

+1 for option (3)!
