### ISSUE TITLE
GitHub Repo Setup

### ISSUE THREAD

**Issue by jdkandersson** [canonical/is-charms-contributing-guide#12]
- is-charms team on GitHub as maintainers
- Varshi, Tom, Mariyan and David as admins (just in case anything happens e.g. people move on)
- branches are auto deleted after merging
- merging PRs via squash is the only option that is allowed
- `main` branch is being used (not `master`) as the default branch
- the default branch is protected and can only be changed via a pull request

**Comment by merkata** [comment]
Very good!
I'd like to propose two additional things:
* number of approvers to be >= 2
* resetting approvals on new commits pushed against the PR
