### ISSUE TITLE
Automatically add reviewers to PRs

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/is-charms-contributing-guide#16]
It is my understanding that automatically adding the IS Charms team as a reviewer can be achieved by adding a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).

**Comment by jdkandersson** [comment]
@arturo-seijas Would you like to add a PR for this one?
