### ISSUE TITLE
What to do with bash commands versus what to do with Python functions

### ISSUE THREAD

**Issue by jdkandersson** [canonical/is-charms-contributing-guide#31]
For our charms it is usually possible to either use bash or use Python to, for example, check a file or make some changes. The proposal is to prefer Python over bash because it is easier to test, more portable and usually easier to read.

**Comment by weiiwang01** [comment]
The bash scripts are mostly due to the limitation of podspec pattern. Most of them are not needed in the sidecar version of the charm.
