### ISSUE TITLE
Standard for pre-commit hooks

### ISSUE THREAD

**Issue by jdkandersson** [canonical/is-charms-contributing-guide#5]
Including pre-commit hooks for:

- Unit tests
- Formatting
  - black
  - isort
  - prettier
- Linting
  - black
  - flake8
  - flake8-docstrings
  - flake8-copyright
  - flake8-builtins
  - pyproject-flake8
  - pep8-naming
  - isort
  - codespell
  - prettier
  - no print function use
  - mypy
For any cases where a rule is disabled, include a comment on why.

**Comment by merkata** [comment]
This seems like a good start and a good set of tools. Nice!

**Comment by jdkandersson** [comment]
Also add:

- bandit (security)
